---
new_page_extension: md
auto_deploy: false
admin_path: "/admin-forestry"
webhook_url: 
sections:
- type: heading
  label: Site Configuration
- type: document
  path: assets/css/main.scss
  label: Main CSS
- type: heading
  label: Post Information
- type: jekyll-posts
  label: Posts
  create: documents
  new_doc_ext: md
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
upload_dir: assets/img/posts
public_path: "/assets/img/posts"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site}}
