name: Deploy Site

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Spelling
        uses: check-spelling/check-spelling@v0.0.22
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add other necessary configurations specific to your project

  set-deploy-type:
    needs: check-spelling
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.set-output.outputs.target }}
    steps:
      - uses: actions/checkout@v4
      - name: get deployment target
        run: |
          TARGET=$(cat DEPLOY_STRATEGY)
          echo "TARGET=$TARGET" >> $GITHUB_ENV

      - name: check if target is valid
        if: success() && !contains(fromJSON('["gh-pages", "firebase", "none"]'), env.TARGET)
        run: echo 'Invalid Deployment Target' && exit 1

      - name: set output to deploy target
        id: set-output
        run: echo "::set-output name=target::${{ env.TARGET }}"

  deploy-none:
    needs: set-deploy-type
    runs-on: ubuntu-latest
    if: needs.set-deploy-type.outputs.target == 'none'
    steps:
      - run: echo 'No Deployment Specified' && exit 0

  deploy-gh-pages:
    needs: set-deploy-type
    runs-on: ubuntu-latest
    if: needs.set-deploy-type.outputs.target == 'gh-pages'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Jekyll Site
        uses: x-limitless-x/jekyll-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

  deploy-firebase:
    needs: set-deploy-type
    runs-on: ubuntu-latest
    if: needs.set-deploy-type.outputs.target == 'firebase'
    steps:
      - uses: actions/checkout@v4
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: build jekyll
        run: |
          bundle install
          bundle exec jekyll build
      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
